# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(235, 169)
        self.welcome_label = QtWidgets.QLabel(Form)
        self.welcome_label.setGeometry(QtCore.QRect(30, 20, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.welcome_label.setFont(font)
        self.welcome_label.setObjectName("welcome_label")
        self.annotate_button = QtWidgets.QPushButton(Form)
        self.annotate_button.setGeometry(QtCore.QRect(80, 50, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.annotate_button.setFont(font)
        self.annotate_button.setObjectName("annotate_button")
        self.train_button = QtWidgets.QPushButton(Form)
        self.train_button.setGeometry(QtCore.QRect(80, 90, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.train_button.setFont(font)
        self.train_button.setObjectName("train_button")
        self.predict_button = QtWidgets.QPushButton(Form)
        self.predict_button.setGeometry(QtCore.QRect(80, 130, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.predict_button.setFont(font)
        self.predict_button.setObjectName("predict_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.welcome_label.setText(_translate("Form", "Welcome to YOLO Gooey"))
        self.annotate_button.setText(_translate("Form", "Annotate"))
        self.train_button.setText(_translate("Form", "Train"))
        self.predict_button.setText(_translate("Form", "Predict"))
